### ISSUE TITLE
More then 50 results in list subs by account

### ISSUE THREAD

**Issue by edencorbin** [umayr/recurly-js#1]
recurly.subscriptions.listByAccount(accountcode, callback) and other calls are limited to 50 results. recurly-js does not seem to support including the cursor in a request to get additional pages. Can this be accomplished through recurly-js? Alternatively, how can I make a raw request facilitated via recurly-js with a cursor/paged result?

**Comment by lorensr** [comment]
I have the same problem. Using `recurly-js/promise`, there doesn't seem to be a way to pass an argument to `recurly.accounts.list()` -- `/v2/accounts`:

https://dev.recurly.com/docs/list-accounts

The arguments I need to use are `per_page` and `cursor` for pagination because there are more than 50 accounts. 

For doing custom API calls, the Recurly docs don't have example xml request bodies, so I'm not sure what to use for `bodyRoot`:

https://github.com/umayr/recurly-js#custom-api-calls

**Comment by edencorbin** [comment]
Did you ever resolve this issue, I worked around it but it is now an issue again. I wonder if you can pass credentials directly into the link via a https request outside of recurly-js.

**Comment by edencorbin** [comment]
Hey think it does work if you pass the cursor into the filter, at least this is available for subscription list.
